ItemSetupAutomationPlatform/Models/IAP_FieldTypes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSetupAutomationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAP_FieldTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IAP_FieldTypes()
        {
            this.IAP_Fields = new HashSet<IAP_Fields>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> UseDataSource { get; set; }
        public Nullable<bool> UseOptions { get; set; }
    
        public virtual IAP_FieldBackEndCode IAP_FieldBackEndCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAP_Fields> IAP_Fields { get; set; }
    }
}

ItemSetupAutomationPlatform/Models/IAP_Fields.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSetupAutomationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAP_Fields
    {
        public long Id { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string FieldLabel { get; set; }
        public Nullable<int> FieldLenght { get; set; }
        public string FieldDataSource { get; set; }
        public string FieldOptions { get; set; }
    }
}

ItemSetupAutomationPlatform/Models/ViewModels/IAP_FieldsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ItemSetupAutomationPlatform.Models.ViewModels
{
    public class IAP_FieldsViewModel
    {
        public long Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        [StringLength(40)]
        public string FieldName { get; set; }

        [Required]
        [Display(Name = "Type")]
        public int FieldType { get; set; }

        
        [Display(Name = "Type")]
        public string FieldTypeDescription { get; set; }

        [Required]
        [Display(Name = "Label")]
        public string FieldLabel { get; set; }

        [Display(Name = "Lenght")]
        public int? FieldLenght { get; set; }

        [Display(Name = "Use Data Source")]
        public bool UseDataSource { get; set; }

        [Display(Name = "Data Source")]
        public string FieldDataSource { get; set; }

        public string FieldOptions { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string FieldDescription { get; set; }
    }
}

ItemSetupAutomationPlatform/Controllers/IAP_FieldsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ItemSetupAutomationPlatform.Models;
using ItemSetupAutomationPlatform.Models.ViewModels;
namespace ItemSetupAutomationPlatform.Controllers
{
    public class IAP_FieldsController : Controller
    {
        // GET: IAP_Fields
        public ActionResult Index()
        {
            List<IAP_FieldsViewModel> fieldsIAP;
            using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
            {
                fieldsIAP = (from d in db.IAP_Fields
                             join c in db.IAP_FieldTypes on d.FieldType equals c.Id
                             select new IAP_FieldsViewModel
                             {
                                 Id = d.Id,
                                 FieldName = d.FieldName,
                                 FieldType = d.FieldType,
                                 FieldTypeDescription = c.Description,
                                 FieldLabel = d.FieldLabel,
                                 FieldDescription = d.FieldDescription,
                                 FieldLenght = d.FieldLenght,
                                 FieldDataSource = d.FieldDataSource,
                                 FieldOptions = d.FieldOptions
                             }).ToList();
            }

            return View(fieldsIAP);
        }

        public ActionResult NewField()
        {
            List<IAP_FieldTypesViewModel> fieldTypes = new List<IAP_FieldTypesViewModel>();
            using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
            {
                fieldTypes =
                (
                    from d in db.IAP_FieldTypes
                    select new IAP_FieldTypesViewModel
                    {
                        Id = d.Id,
                        Description = d.Description
                    }).ToList();

            }

            List<SelectListItem> items = fieldTypes.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Description.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = items;
            return View();
        }

        [HttpPost]
        public ActionResult NewField(IAP_FieldsViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
                    {
                        var IAP_field = new Models.IAP_Fields();
                        IAP_field.Id = model.Id;
                        IAP_field.FieldName = model.FieldName;
                        IAP_field.FieldType = model.FieldType;
                        IAP_field.FieldLabel = model.FieldLabel;
                        IAP_field.FieldDescription = model.FieldDescription;
                        IAP_field.FieldLenght = model.FieldLenght;
                        IAP_field.FieldDataSource = model.FieldDataSource;
                        IAP_field.FieldOptions = model.FieldOptions;
                        db.IAP_Fields.Add(IAP_field);
                        db.SaveChanges();
                    }

                    return Redirect("~/IAP_Fields/");
                }

                return View(model);

            }
            catch (Exception error)
            {
                throw new Exception(error.Message);
            }
        }

        public ActionResult EditField(string fieldName)
        {
            IAP_FieldsViewModel model = new IAP_FieldsViewModel();
            List<IAP_FieldTypesViewModel> fieldTypes = new List<IAP_FieldTypesViewModel>();
            using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
            {
                fieldTypes =
                (
                    from d in db.IAP_FieldTypes
                    select new IAP_FieldTypesViewModel
                    {
                        Id = d.Id,
                        Description = d.Description
                    }).ToList();

            }

            List<SelectListItem> items = fieldTypes.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Description.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = items;
            using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
            {
                var oField = db.IAP_Fields.Find(fieldName);
                model.Id = oField.Id;
                model.FieldName = oField.FieldName;
                model.FieldLabel = oField.FieldLabel;
                model.FieldDescription = oField.FieldDescription;
                model.FieldType = oField.FieldType;
                model.FieldLenght = oField.FieldLenght;
                model.FieldDataSource = oField.FieldDataSource;
                model.FieldOptions = oField.FieldOptions;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult EditField(IAP_FieldsViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
                    {
                        var IAP_field = db.IAP_Fields.Find(model.FieldName);
                        //IAP_field.Id = model.Id;
                        IAP_field.FieldName = model.FieldName;
                        IAP_field.FieldType = model.FieldType;
                        IAP_field.FieldLabel = model.FieldLabel;
                        IAP_field.FieldDescription = model.FieldDescription;
                        IAP_field.FieldLenght = model.FieldLenght;
                        IAP_field.FieldDataSource = model.FieldDataSource;
                        IAP_field.FieldOptions = model.FieldOptions;

                        db.Entry(IAP_field).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/IAP_Fields/");
                }

                return View(model);

            }
            catch (Exception error)
            {
                throw new Exception(error.Message);
            }
        }
        
        [HttpGet]
        public ActionResult DeleteField(string fieldName)
        {
            using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
            {
                var oField = db.IAP_Fields.Find(fieldName);
                db.IAP_Fields.Remove(oField);
                db.SaveChanges();
            }
            return Redirect("~/IAP_FIelds/");
        }

        public ActionResult ValidateDataSourceRequired(int fieldType)
        {
            bool? dataSourceRequired = false;
            using (ItemAutomationPlatformEntities db = new ItemAutomationPlatformEntities())
            {
                dataSourceRequired = db.IAP_FieldTypes.Find(fieldType).UseDataSource;
            }

            return View(dataSourceRequired);
        }
    }
}

ItemSetupAutomationPlatform/Views/IAP_Fields/EditField.cshtml
@model ItemSetupAutomationPlatform.Models.ViewModels.IAP_FieldsViewModel
@{
    ViewBag.Title = "Workflow Fields Edit";
    List<SelectListItem> fieldTypes = (List<SelectListItem>)ViewBag.items;
}

<h2>@ViewBag.Title</h2>
<head>
    <script src="../Scripts/jquery-3.3.1.min.js"></script>
</head>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#FieldType').change(function () {
                var value = $(this).val();
                if (value == '3') {
                    $('.dsControl').show();
                    
                } else {
                    $('.dsControl').hide();
                }
            });
        });</script>
}

@using (Html.BeginForm("EditField", "IAP_Fields", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(model => model.FieldName)
            <br />
            <br />
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.FieldName)
                    @Html.TextBoxFor(model => model.FieldName, "", new { @class = "form-control" , @readonly = "true"})
                    @Html.ValidationMessageFor(model => model.FieldName, null, new { @class = "text-danger" })
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.FieldLabel)
                    @Html.TextBoxFor(model => model.FieldLabel, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FieldLabel, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.FieldDescription)
                    @Html.TextBoxFor(model => model.FieldDescription, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FieldDescription, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.FieldType, new { id = "FieldTypeLabel" })
                    @Html.DropDownListFor(model => model.FieldType, fieldTypes, "Select an Option", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FieldType, null, new { @class = "text-danger" })
                </div>
                <div class="col"></div>
            </div>
            <br />
            <div class="dsControl" style="display: none;">
                @Html.LabelFor(model => model.FieldDataSource)
                @Html.TextBoxFor(model => model.FieldDataSource, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FieldDataSource, null, new { @class = "text-danger" })
            </div>
            <br />
            <div style="text-align:right:">
                <input value="Save" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}

ItemSetupAutomationPlatform/Views/IAP_Fields/Index.cshtml
@model List<ItemSetupAutomationPlatform.Models.ViewModels.IAP_FieldsViewModel>
@{
    ViewBag.Title = "Workflow Fields Maintenance";
}

<h2>@ViewBag.Title</h2>
<br />
<br />
<div class="row" style="text-align:right;padding:5px;">
    <a href="~/IAP_Fields/NewField" class="btn btn-primary">New</a>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Label</th>
                <th>Description</th>
                <th>Type</th>
                <th></th>
            </tr>
            @foreach (var oElement in Model)
            {
                <tr>
                    <td>@oElement.FieldName</td>
                    <td>@oElement.FieldLabel</td>
                    <td>@oElement.FieldDescription</td>
                    <td>@oElement.FieldTypeDescription</td>
                    <td>
                        @Html.ActionLink("Edit", "EditField", "IAP_Fields", new { FieldName = @oElement.FieldName }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Delete", "DeleteField", "IAP_Fields", new { FieldName = @oElement.FieldName }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </table>
    </div>

</div>

ItemSetupAutomationPlatform/Views/IAP_Fields/NewField.cshtml
@model ItemSetupAutomationPlatform.Models.ViewModels.IAP_FieldsViewModel
@{
    ViewBag.Title = "New Field";
    List<SelectListItem> fieldTypes = (List<SelectListItem>)ViewBag.items;
}
<head>
    <script src="../Scripts/jquery-3.3.1.min.js"></script>
</head>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#FieldType').change(function () {
                var value = $(this).val();
                //var x = $('#ValidateDataSourceRequired')
                if (value == '3') {
                    $('.dsControl').show();
                    
                } else {
                    $('.dsControl').hide();
                }
            });
        });</script>
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("NewField", "IAP_Fields", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <br />
            <br />
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.FieldName)
                    @Html.TextBoxFor(model => model.FieldName, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FieldName, null, new { @class = "text-danger" })
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.FieldLabel)
                    @Html.TextBoxFor(model => model.FieldLabel, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FieldLabel, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.FieldDescription)
                    @Html.TextBoxFor(model => model.FieldDescription, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FieldDescription, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.FieldType, new { id = "FieldTypeLabel" })
                    @Html.DropDownListFor(model => model.FieldType, fieldTypes, "Select an Option", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FieldType, null, new { @class = "text-danger" })
                </div>
                <div class="col"></div>
            </div>            
            <br />
            <div class="dsControl" style="display: none;">
                @Html.LabelFor(model => model.FieldDataSource)
                @Html.TextBoxFor(model => model.FieldDataSource, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FieldDataSource, null, new { @class = "text-danger" })
            </div>
            <br />
            <div style="text-align:right:">
                <input value="Save" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}